<?php
$emojis = array(
    new Option(OptionType::Text, "😀"),
    new Option(OptionType::Text, "😃"),
    new Option(OptionType::Text, "😄"),
    new Option(OptionType::Text, "😁"),
    new Option(OptionType::Text, "😆"),
    new Option(OptionType::Text, "😅"),
    new Option(OptionType::Text, "😂"),
    new Option(OptionType::Text, "🤣"),
    new Option(OptionType::Text, "☺️"),
    new Option(OptionType::Text, "😊"),
    new Option(OptionType::Text, "😇"),
    new Option(OptionType::Text, "🙂"),
    new Option(OptionType::Text, "🙃"),
    new Option(OptionType::Text, "😉"),
    new Option(OptionType::Text, "😌"),
    new Option(OptionType::Text, "😍"),
    new Option(OptionType::Text, "😘"),
    new Option(OptionType::Text, "😗"),
    new Option(OptionType::Text, "😙"),
    new Option(OptionType::Text, "😚"),
    new Option(OptionType::Text, "😋"),
    new Option(OptionType::Text, "😜"),
    new Option(OptionType::Text, "😝"),
    new Option(OptionType::Text, "😛"),
    new Option(OptionType::Text, "🤑"),
    new Option(OptionType::Text, "🤗"),
    new Option(OptionType::Text, "🤓"),
    new Option(OptionType::Text, "😎"),
    new Option(OptionType::Text, "🤡"),
    new Option(OptionType::Text, "🤠"),
    new Option(OptionType::Text, "😏"),
    new Option(OptionType::Text, "😒"),
    new Option(OptionType::Text, "😞"),
    new Option(OptionType::Text, "😔"),
    new Option(OptionType::Text, "😟"),
    new Option(OptionType::Text, "😕"),
    new Option(OptionType::Text, "🙁"),
    new Option(OptionType::Text, "☹️"),
    new Option(OptionType::Text, "😣"),
    new Option(OptionType::Text, "😖"),
    new Option(OptionType::Text, "😤"),
    new Option(OptionType::Text, "😐"),
    new Option(OptionType::Text, "😑"),
    new Option(OptionType::Text, "😧"),
    new Option(OptionType::Text, "😳"),
    new Option(OptionType::Text, "😱"),
    new Option(OptionType::Text, "😢"),
    new Option(OptionType::Text, "😥"),
    new Option(OptionType::Text, "🤤"),
    new Option(OptionType::Text, "😭"),
    new Option(OptionType::Text, "😓"),
    new Option(OptionType::Text, "😪"),
    new Option(OptionType::Text, "😴"),
    new Option(OptionType::Text, "🙄"),
    new Option(OptionType::Text, "🤔"),
    new Option(OptionType::Text, "😬"),
    new Option(OptionType::Text, "🤐"),
    new Option(OptionType::Text, "🤧"),
    new Option(OptionType::Text, "😷"),
    new Option(OptionType::Text, "💩"),
    new Option(OptionType::Text, "😈"),
    new Option(OptionType::Text, "💀"),
    new Option(OptionType::Text, "👍"),
    new Option(OptionType::Text, "👎"),
    new Option(OptionType::Text, "🤞"),
    new Option(OptionType::Text, "👌"),
    new Option(OptionType::Text, "👋"),
    new Option(OptionType::Text, "🐣"),
    new Option(OptionType::Text, "🐥"),
    new Option(OptionType::Text, "🐬"),
    new Option(OptionType::Text, "🐳"),
    new Option(OptionType::Text, "🔥"),
    new Option(OptionType::Text, "☀️"),
    new Option(OptionType::Text, "🌈"),
    new Option(OptionType::Text, "💰"),
    new Option(OptionType::Text, "🎉"),
    new Option(OptionType::Text, "🎊"),
    new Option(OptionType::Text, "❤️"),
    new Option(OptionType::Text, "💕"),
    new Option(OptionType::Text, "💞"),
    new Option(OptionType::Text, "💗"),
    new Option(OptionType::Text, "💖"),
    new Option(OptionType::Text, "💘"),
    new Option(OptionType::Text, "💝"),
    new Option(OptionType::Text, "🏳️‍🌈"),
    new Option(OptionType::Text, "🌟"),
    new Option(OptionType::Text, "⭐"),
    new Option(OptionType::Text, "✨"),
    new Option(OptionType::Text, "💥")
);

$countries = array(
    new Option(OptionType::Text, "Afghanistan"),
    new Option(OptionType::Text, "land Islands"),
    new Option(OptionType::Text, "Albania"),
    new Option(OptionType::Text, "Algeria"),
    new Option(OptionType::Text, "American Samoa"),
    new Option(OptionType::Text, "AndorrA"),
    new Option(OptionType::Text, "Angola"),
    new Option(OptionType::Text, "Anguilla"),
    new Option(OptionType::Text, "Antarctica"),
    new Option(OptionType::Text, "Antigua and Barbuda"),
    new Option(OptionType::Text, "Argentina"),
    new Option(OptionType::Text, "Armenia"),
    new Option(OptionType::Text, "Aruba"),
    new Option(OptionType::Text, "Australia"),
    new Option(OptionType::Text, "Austria"),
    new Option(OptionType::Text, "Azerbaijan"),
    new Option(OptionType::Text, "Bahamas"),
    new Option(OptionType::Text, "Bahrain"),
    new Option(OptionType::Text, "Bangladesh"),
    new Option(OptionType::Text, "Barbados"),
    new Option(OptionType::Text, "Belarus"),
    new Option(OptionType::Text, "Belgium"),
    new Option(OptionType::Text, "Belize"),
    new Option(OptionType::Text, "Benin"),
    new Option(OptionType::Text, "Bermuda"),
    new Option(OptionType::Text, "Bhutan"),
    new Option(OptionType::Text, "Bolivia"),
    new Option(OptionType::Text, "Bosnia and Herzegovina"),
    new Option(OptionType::Text, "Botswana"),
    new Option(OptionType::Text, "Bouvet Island"),
    new Option(OptionType::Text, "Brazil"),
    new Option(OptionType::Text, "British Indian Ocean Territory"),
    new Option(OptionType::Text, "Brunei Darussalam"),
    new Option(OptionType::Text, "Bulgaria"),
    new Option(OptionType::Text, "Burkina Faso"),
    new Option(OptionType::Text, "Burundi"),
    new Option(OptionType::Text, "Cambodia"),
    new Option(OptionType::Text, "Cameroon"),
    new Option(OptionType::Text, "Canada"),
    new Option(OptionType::Text, "Cape Verde"),
    new Option(OptionType::Text, "Cayman Islands"),
    new Option(OptionType::Text, "Central African Republic"),
    new Option(OptionType::Text, "Chad"),
    new Option(OptionType::Text, "Chile"),
    new Option(OptionType::Text, "China"),
    new Option(OptionType::Text, "Christmas Island"),
    new Option(OptionType::Text, "Cocos (Keeling) Islands"),
    new Option(OptionType::Text, "Colombia"),
    new Option(OptionType::Text, "Comoros"),
    new Option(OptionType::Text, "Congo"),
    new Option(OptionType::Text, "Cook Islands"),
    new Option(OptionType::Text, "Costa Rica"),
    new Option(OptionType::Text, "Cote D'Ivoire"),
    new Option(OptionType::Text, "Croatia"),
    new Option(OptionType::Text, "Cuba"),
    new Option(OptionType::Text, "Cyprus"),
    new Option(OptionType::Text, "Czech Republic"),
    new Option(OptionType::Text, "Denmark"),
    new Option(OptionType::Text, "Djibouti"),
    new Option(OptionType::Text, "Dominica"),
    new Option(OptionType::Text, "Dominican Republic"),
    new Option(OptionType::Text, "Ecuador"),
    new Option(OptionType::Text, "Egypt"),
    new Option(OptionType::Text, "El Salvador"),
    new Option(OptionType::Text, "Equatorial Guinea"),
    new Option(OptionType::Text, "Eritrea"),
    new Option(OptionType::Text, "Estonia"),
    new Option(OptionType::Text, "Ethiopia"),
    new Option(OptionType::Text, "Falkland Islands (Malvinas)"),
    new Option(OptionType::Text, "Faroe Islands"),
    new Option(OptionType::Text, "Fiji"),
    new Option(OptionType::Text, "Finland"),
    new Option(OptionType::Text, "France"),
    new Option(OptionType::Text, "French Guiana"),
    new Option(OptionType::Text, "French Polynesia"),
    new Option(OptionType::Text, "French Southern Territories"),
    new Option(OptionType::Text, "Gabon"),
    new Option(OptionType::Text, "Gambia"),
    new Option(OptionType::Text, "Georgia"),
    new Option(OptionType::Text, "Germany"),
    new Option(OptionType::Text, "Ghana"),
    new Option(OptionType::Text, "Gibraltar"),
    new Option(OptionType::Text, "Greece"),
    new Option(OptionType::Text, "Greenland"),
    new Option(OptionType::Text, "Grenada"),
    new Option(OptionType::Text, "Guadeloupe"),
    new Option(OptionType::Text, "Guam"),
    new Option(OptionType::Text, "Guatemala"),
    new Option(OptionType::Text, "Guernsey"),
    new Option(OptionType::Text, "Guinea"),
    new Option(OptionType::Text, "Guinea-Bissau"),
    new Option(OptionType::Text, "Guyana"),
    new Option(OptionType::Text, "Haiti"),
    new Option(OptionType::Text, "Heard Island and Mcdonald Islands"),
    new Option(OptionType::Text, "Holy See (Vatican City State)"),
    new Option(OptionType::Text, "Honduras"),
    new Option(OptionType::Text, "Hong Kong"),
    new Option(OptionType::Text, "Hungary"),
    new Option(OptionType::Text, "Iceland"),
    new Option(OptionType::Text, "India"),
    new Option(OptionType::Text, "Indonesia"),
    new Option(OptionType::Text, "Iran"),
    new Option(OptionType::Text, "Iraq"),
    new Option(OptionType::Text, "Ireland"),
    new Option(OptionType::Text, "Isle of Man"),
    new Option(OptionType::Text, "Israel"),
    new Option(OptionType::Text, "Italy"),
    new Option(OptionType::Text, "Jamaica"),
    new Option(OptionType::Text, "Japan"),
    new Option(OptionType::Text, "Jersey"),
    new Option(OptionType::Text, "Jordan"),
    new Option(OptionType::Text, "Kazakhstan"),
    new Option(OptionType::Text, "Kenya"),
    new Option(OptionType::Text, "Kiribati"),
    new Option(OptionType::Text, "Korea"),
    new Option(OptionType::Text, "Kuwait"),
    new Option(OptionType::Text, "Kyrgyzstan"),
    new Option(OptionType::Text, "Lao People's Democratic Republic"),
    new Option(OptionType::Text, "Latvia"),
    new Option(OptionType::Text, "Lebanon"),
    new Option(OptionType::Text, "Lesotho"),
    new Option(OptionType::Text, "Liberia"),
    new Option(OptionType::Text, "Libyan Arab Jamahiriya"),
    new Option(OptionType::Text, "Liechtenstein"),
    new Option(OptionType::Text, "Lithuania"),
    new Option(OptionType::Text, "Luxembourg"),
    new Option(OptionType::Text, "Macao"),
    new Option(OptionType::Text, "Macedonia"),
    new Option(OptionType::Text, "Madagascar"),
    new Option(OptionType::Text, "Malawi"),
    new Option(OptionType::Text, "Malaysia"),
    new Option(OptionType::Text, "Maldives"),
    new Option(OptionType::Text, "Mali"),
    new Option(OptionType::Text, "Malta"),
    new Option(OptionType::Text, "Marshall Islands"),
    new Option(OptionType::Text, "Martinique"),
    new Option(OptionType::Text, "Mauritania"),
    new Option(OptionType::Text, "Mauritius"),
    new Option(OptionType::Text, "Mayotte"),
    new Option(OptionType::Text, "Mexico"),
    new Option(OptionType::Text, "Micronesia"),
    new Option(OptionType::Text, "Moldova"),
    new Option(OptionType::Text, "Monaco"),
    new Option(OptionType::Text, "Mongolia"),
    new Option(OptionType::Text, "Montenegro"),
    new Option(OptionType::Text, "Montserrat"),
    new Option(OptionType::Text, "Morocco"),
    new Option(OptionType::Text, "Mozambique"),
    new Option(OptionType::Text, "Myanmar"),
    new Option(OptionType::Text, "Namibia"),
    new Option(OptionType::Text, "Nauru"),
    new Option(OptionType::Text, "Nepal"),
    new Option(OptionType::Text, "Netherlands"),
    new Option(OptionType::Text, "Netherlands Antilles"),
    new Option(OptionType::Text, "New Caledonia"),
    new Option(OptionType::Text, "New Zealand"),
    new Option(OptionType::Text, "Nicaragua"),
    new Option(OptionType::Text, "Niger"),
    new Option(OptionType::Text, "Nigeria"),
    new Option(OptionType::Text, "Niue"),
    new Option(OptionType::Text, "Norfolk Island"),
    new Option(OptionType::Text, "Northern Mariana Islands"),
    new Option(OptionType::Text, "Norway"),
    new Option(OptionType::Text, "Oman"),
    new Option(OptionType::Text, "Pakistan"),
    new Option(OptionType::Text, "Palau"),
    new Option(OptionType::Text, "Palestinian Territory"),
    new Option(OptionType::Text, "Panama"),
    new Option(OptionType::Text, "Papua New Guinea"),
    new Option(OptionType::Text, "Paraguay"),
    new Option(OptionType::Text, "Peru"),
    new Option(OptionType::Text, "Philippines"),
    new Option(OptionType::Text, "Pitcairn"),
    new Option(OptionType::Text, "Poland"),
    new Option(OptionType::Text, "Portugal"),
    new Option(OptionType::Text, "Puerto Rico"),
    new Option(OptionType::Text, "Qatar"),
    new Option(OptionType::Text, "Reunion"),
    new Option(OptionType::Text, "Romania"),
    new Option(OptionType::Text, "Russian Federation"),
    new Option(OptionType::Text, "RWANDA"),
    new Option(OptionType::Text, "Saint Helena"),
    new Option(OptionType::Text, "Saint Kitts and Nevis"),
    new Option(OptionType::Text, "Saint Lucia"),
    new Option(OptionType::Text, "Saint Pierre and Miquelon"),
    new Option(OptionType::Text, "Saint Vincent and the Grenadines"),
    new Option(OptionType::Text, "Samoa"),
    new Option(OptionType::Text, "San Marino"),
    new Option(OptionType::Text, "Sao Tome and Principe"),
    new Option(OptionType::Text, "Saudi Arabia"),
    new Option(OptionType::Text, "Senegal"),
    new Option(OptionType::Text, "Serbia"),
    new Option(OptionType::Text, "Seychelles"),
    new Option(OptionType::Text, "Sierra Leone"),
    new Option(OptionType::Text, "Singapore"),
    new Option(OptionType::Text, "Slovakia"),
    new Option(OptionType::Text, "Slovenia"),
    new Option(OptionType::Text, "Solomon Islands"),
    new Option(OptionType::Text, "Somalia"),
    new Option(OptionType::Text, "South Africa"),
    new Option(OptionType::Text, "South Georgia and the South Sandwich Islands"),
    new Option(OptionType::Text, "Spain"),
    new Option(OptionType::Text, "Sri Lanka"),
    new Option(OptionType::Text, "Sudan"),
    new Option(OptionType::Text, "Suriname"),
    new Option(OptionType::Text, "Svalbard and Jan Mayen"),
    new Option(OptionType::Text, "Swaziland"),
    new Option(OptionType::Text, "Sweden"),
    new Option(OptionType::Text, "Switzerland"),
    new Option(OptionType::Text, "Syrian Arab Republic"),
    new Option(OptionType::Text, "Taiwan"),
    new Option(OptionType::Text, "Tajikistan"),
    new Option(OptionType::Text, "Tanzania"),
    new Option(OptionType::Text, "Thailand"),
    new Option(OptionType::Text, "Timor-Leste"),
    new Option(OptionType::Text, "Togo"),
    new Option(OptionType::Text, "Tokelau"),
    new Option(OptionType::Text, "Tonga"),
    new Option(OptionType::Text, "Trinidad and Tobago"),
    new Option(OptionType::Text, "Tunisia"),
    new Option(OptionType::Text, "Turkey"),
    new Option(OptionType::Text, "Turkmenistan"),
    new Option(OptionType::Text, "Turks and Caicos Islands"),
    new Option(OptionType::Text, "Tuvalu"),
    new Option(OptionType::Text, "Uganda"),
    new Option(OptionType::Text, "Ukraine"),
    new Option(OptionType::Text, "United Arab Emirates"),
    new Option(OptionType::Text, "United Kingdom"),
    new Option(OptionType::Text, "United States"),
    new Option(OptionType::Text, "United States Minor Outlying Islands"),
    new Option(OptionType::Text, "Uruguay"),
    new Option(OptionType::Text, "Uzbekistan"),
    new Option(OptionType::Text, "Vanuatu"),
    new Option(OptionType::Text, "Venezuela"),
    new Option(OptionType::Text, "Viet Nam"),
    new Option(OptionType::Text, "Virgin Islands, British"),
    new Option(OptionType::Text, "Virgin Islands, U.S."),
    new Option(OptionType::Text, "Wallis and Futuna"),
    new Option(OptionType::Text, "Western Sahara"),
    new Option(OptionType::Text, "Yemen"),
    new Option(OptionType::Text, "Zambia"),
    new Option(OptionType::Text, "Zimbabwe")
);
